# Site settings
name: Minh-Phuc Bui
title: Minh-Phuc Bui | Front End Web Developer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://phucbm.github.io/
baseurl: ''
email: hiphucbui@gmail.com
cover: https://phucbm.github.io/img/og.png
logo: https://phucbm.github.io/img/avatar.png
resume: https://www.linkedin.com/in/phucbm/
social:
  - title: email
    url: mailto:hiphucbui@gmail.com
  - title: codepen
    url: http://codepen.io/phucbui
  - title: github
    url: https://github.com/phucbm
  - title: linkedin
    url: https://www.linkedin.com/in/phucbm

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
